services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cvdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  t3-app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    environment:
      - GENERIC_TIMEZONE=Europe/Berlin
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
    ports:
      - "5678:5678"
    depends_on:
      - t3-app
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  db_data:
  n8n_data:
